import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import '@/app/globals.css';

// Fuente de texto Montserrat con soporte para caracteres latinos
const montserrat = Montserrat({ subsets: ["latin"] });

// Metadatos de la aplicación
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Componente principal que envuelve a toda la aplicación
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // Devuelve el contenido de la aplicación
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}