import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/globals.css";

// Fuente de texto de Google Fonts
const inter = Inter({ subsets: ["latin"] });

// Metadatos de la aplicación
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Componente principal que envuelve a toda la aplicación
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // Devuelve el contenido de la aplicación
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}